services:
  - type: web
    name: Twitter_Sentiment_Analysis_Project
    env: python-3.10.13
    region: frankfurt
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
